name: xnap-segmentation
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - tqdm
  - matplotlib
  - pillow
  - pip:
      - torch
      - torchvision
      - wandb
      - ipykernel
      - tensorboard
